##
# File: getjobs.yml
##
---
- hosts: "{{ acthost }}"
  # if you need to disable logging no_log: True
  no_log: True
  remote_user: root
  gather_facts: false
  port: 26

  vars:
     debug_file: debug.txt
     debug_filename: /tmp/debug.txt

  vars_prompt:
    name: "job_id"
    prompt: "Enter the Actifio job name?" 
    private: no

  tasks:

  - name: Find out the hostID   # capitalize | lower
    action: shell udsinfo lsjobhistory {{ job_id | capitalize }} -delim , | grep hostid | cut -d, -f2
    register: hostid
  - debug:
      msg: "{{ hostid.stdout }}"

  - name: Find out the appID
    action: shell udsinfo lsjobhistory {{ job_id | capitalize }} -delim , | grep appid | cut -d, -f2
    register: appid
  - debug:
      msg: "{{ appid.stdout }}"

  - name: Find out the hostname
    action: shell udsinfo lshost {{ hostid.stdout }} -delim , | grep hostname | cut -d, -f2
    register: hostname2
  - debug:
      msg: "{{ hostname2.stdout }}"

  - name: Run SARG header
    shell: |
       echo -e "\n--------------------------------------------------------------\n" > {{ debug_filename }}

  - name: Run SARG commands
    shell: |
       echo "Command: {{item}} " >> {{ debug_filename }}
       {{item}} >> {{ debug_filename }}
       echo -e "\n--------------------------------------------------------------\n" >> {{ debug_filename }}
    with_items:
       - reportconnectors -w -a {{ hostid.stdout }}
       - reportapps -w -a {{ appid.stdout }}
       - udsinfo lshost -delim =  {{ hostid.stdout }}
       - udsinfo lsapplication -delim =  {{ appid.stdout }}
       - udsinfo lsjobhistory {{ job_id  | capitalize }}
       - udstask fetchconnectorlogs -host {{ hostid.stdout }}

  - name: Gather data
    shell: |
      echo "grep {{ job_id  | capitalize }} /dumps/udppm.log" >> {{ debug_filename }}
      grep {{ job_id  | capitalize }} /dumps/udppm.log >> {{ debug_filename }}
      echo -e "\n--------------------------------------------------------------\n" >> {{ debug_filename }}
      echo "grep {{ job_id  | capitalize }} /dumps/psrv.log.0" >> {{ debug_filename }}
      grep {{ job_id  | capitalize }} /dumps/psrv.log.0 >> {{ debug_filename }}
      echo -e "\n--------------------------------------------------------------\n" >> {{ debug_filename }}
      echo "grep {{ job_id  | capitalize }} /dumps/tmp/{{ hostname2.stdout }}/UDSAgent.log " >> {{ debug_filename }}
      grep {{ job_id  | capitalize }} /dumps/tmp/{{ hostname2.stdout }}/UDSAgent.log >> {{ debug_filename }}
      echo -e "\n--------------------------------------------------------------\n" >> {{ debug_filename }}

  - name: transfer file
    # copy remote file into local machine
    # force: no   --- will only copy the file if the file does not exist on the remote server.
    fetch:
      src: "{{ debug_filename }}"
      dest: ./{{ job_id | capitalize }}.txt 
      flat: yes
  - name: Cleanup the {{ debug_filename }} file
    file:
      path: "{{ debug_filename }}"
      state: absent
